/*

Compile with `-g:none` to forgo all debug symbols:

```
$ javac -g:none Factorial.java
```

Inspect generated bytecode with:

```
$ javap -v Factorial.java
```

*/

public class Factorial {
  public static void main(String[] args) {
    int r = factorial(5);
    System.out.println(Integer.toString(r));
  }

  public static int factorial(int n) {
    int r = 1;

    while (n > 0) {
      r = n * r;
      n--;
    }

    return r;
  }
}
